---
- name: Set hostname
  hostname:
    name: "mythic"
  become: yes

- name: Update and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
  become: yes

- name: Clone Mythic Git repo
  git:
    repo: https://github.com/its-a-feature/Mythic
    dest: "{{ ansible_env.HOME }}/mythic"
    force: yes

- name: Upload custom Mythic config.json
  copy:
    src: ./files/config.json
    dest: "{{ ansible_env.HOME }}/mythic/mythic-docker/config.json"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Install Docker using Mythic-provided script
  command: "{{ ansible_env.HOME }}/mythic/install_docker_{{ ansible_distribution|lower }}.sh"
  become: yes
